PREFIX=arm-none-eabi-

include ../Makefile.config

MCPU=cortex-m3
CFLAGS+=-mthumb
# give libos.a twice so that -lgcc can find memcpy
LDADD=libos.a

OBJS = init-m.o arm-id.o common.o printk.o systick-m.o irq-m.o mpu.o

TARGETS = minimal-kern.bin
all: $(TARGETS)

minimal-kern.elf: cortexm.ld example-minimal.o libos.a

$(TARGETS): common.ld

include ../Makefile.common

vpath % ../arm ../arm/arm7m ../arm/example
