AS=$(PREFIX)as
GCC=$(PREFIX)gcc
GXX=$(PREFIX)g++
AR=$(PREFIX)ar
OBJCOPY=$(PREFIX)objcopy

DEBUG=-g
OPT=-Os

CFLAGS=-mcpu=$(MCPU) -MMD -ffreestanding -nodefaultlibs $(DEBUG) $(OPT)
LDFLAGS=-static

CFLAGS+=$(SRCDIRS:%=-I../%)
LDFLAGS+=$(SRCDIRS:%=-L../%)

CFLAGS += -Wall -Wextra -Wno-unused-parameter -Werror
