PREFIX=arm-none-eabi-
AS=$(PREFIX)as
GCC=$(PREFIX)gcc
GXX=$(PREFIX)g++
AR=$(PREFIX)ar
OBJCOPY=$(PREFIX)objcopy

DEBUG=-g
OPT=-Os

ASFLAGS=-mcpu=$(MCPU) -W --fatal-warnings $(DEBUG)
CFLAGS=-mcpu=$(MCPU) -MMD -I. -I.. -ffreestanding -nodefaultlibs $(DEBUG) $(OPT) -Wall -Wextra -Werror
LDFLAGS=-static
